### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by JulianSMoore** [kubaPod/DevTools#3]
Hi Kuba - I'm trying to track down the source of a front end issue that causes MMA to be "not responding" for 5-10s at a time, and not being familiar with paclets and so on haven't been able to work out how to uninstall devtools and or MPM so I can eliminate them as causes. Can you advise? (I just dragged out the devtools package from the folder but Ctrl+1 still works, just doesn't find the devtools any more so I haven't achieved much yet) Thanks, Julian

PS I thought the front end issue might have been due to Eclipse, graphics drivers, ... but the issue persists even when not using Workbench in Eclipse and I've swapped around the graphics from internal CPU to external graphics card and back without resolving the issue...

**Comment by kubaPod** [comment]
It should be enough to run:

    PacletUninstall@"DevTools"
    PacletUninstall@"MPM"

**Comment by JulianSMoore** [comment]
Done; will advise whether the problem necessitating temp removal remains or not in due course. Thx.

**Comment by kubaPod** [comment]
@JulianSMoore  ok, good luck. The only lag I can think of is when the menu is used first time in a session, the cache needs to be loaded etc. But it should not be so long and only happen on Ctrl+1 event.

**Comment by kubaPod** [comment]
@JulianSMoore I added information about uninstall procedure to README.md

**Comment by JulianSMoore** [comment]
Just to follow up as promised; following uninstall the issue remained, so it is not your code (I didn't expect it would be, but the test is the test). I'll reinstall later. Thanks.
